# Generated by Django 4.1.7 on 2023-05-19 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='başlık')),
                ('text', models.TextField(max_length=300, verbose_name='açıklama')),
                ('price', models.FloatField(verbose_name='fiyat')),
                ('stok', models.IntegerField(verbose_name='adet')),
                ('date_now', models.DateField(auto_now_add=True, verbose_name='tarih ve saat')),
                ('stars', models.FloatField(verbose_name='ürün puanı')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='kulanıcı')),
            ],
        ),
    ]
