# Generated by Django 4.1.7 on 2023-05-20 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0027_alter_tour_city'),
        ('appUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.tour', verbose_name='turadı')),
            ],
        ),
        migrations.DeleteModel(
            name='Producht',
        ),
    ]
