# Generated by Django 4.1.7 on 2023-05-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0003_basket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='quanity',
            field=models.IntegerField(blank=True, null=True, verbose_name='adet'),
        ),
        migrations.AddField(
            model_name='basket',
            name='total_price',
            field=models.FloatField(blank=True, null=True, verbose_name='toplam fiyat'),
        ),
    ]
