# Generated by Django 4.1.7 on 2023-05-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0004_basket_quanity_basket_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='total_price',
        ),
    ]
