# Generated by Django 4.1.7 on 2023-05-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0005_remove_basket_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='total_price',
            field=models.FloatField(null=True, verbose_name='toplam fiyat'),
        ),
    ]
