# Generated by Django 4.1.7 on 2023-05-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0008_alter_basket_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='total_price',
            field=models.CharField(max_length=50, null=True, verbose_name='toplam'),
        ),
    ]
