# Generated by Django 4.1.7 on 2023-05-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0012_alter_basket_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='total_price',
            field=models.IntegerField(null=True, verbose_name='toplam fiyat'),
        ),
    ]
