# Generated by Django 4.1.7 on 2023-05-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0013_alter_basket_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='total_price',
            new_name='totalls_price',
        ),
    ]
