# Generated by Django 4.1.7 on 2023-05-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0014_rename_total_price_basket_totalls_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='totalls_price',
            new_name='total_price',
        ),
    ]
