# Generated by Django 4.1.7 on 2023-05-21 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0018_basket_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
