# Generated by Django 4.1.7 on 2023-05-21 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0019_rename_quanity_basket_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='quantity',
            new_name='quanity',
        ),
    ]
