# Generated by Django 4.1.7 on 2023-05-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0022_basket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
