# Generated by Django 4.1.7 on 2023-05-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0023_basket_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='basket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
