# Generated by Django 4.1.7 on 2023-05-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0024_remove_basket_is_paid_basket_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='is_paid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
