# Generated by Django 4.1.7 on 2023-05-23 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0050_remove_userinfo_order_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appUser', '0025_basket_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='oldBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quanity', models.IntegerField(null=True, verbose_name='adet')),
                ('total_price', models.IntegerField(null=True, verbose_name='toplam fiyat')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_paid', models.BooleanField(default=False, null=True)),
                ('tuors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.tour', verbose_name='turadı')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.userinfo', verbose_name='kullanıcı')),
            ],
        ),
    ]
