# Generated by Django 4.1.7 on 2023-05-23 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0026_oldbasket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='old_basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appUser.oldbasket'),
        ),
    ]
