# Generated by Django 4.1.7 on 2023-05-23 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0027_basket_old_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='old_basket',
        ),
        migrations.DeleteModel(
            name='oldBasket',
        ),
    ]
