# Generated by Django 4.1.7 on 2023-05-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0028_remove_basket_old_basket_delete_oldbasket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='basket',
            name='is_past_order',
            field=models.BooleanField(default=False),
        ),
    ]
