# Generated by Django 4.1.7 on 2023-05-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0029_remove_basket_created_at_remove_basket_is_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='is_past_order',
        ),
        migrations.AddField(
            model_name='basket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='is_paid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
