# Generated by Django 4.1.7 on 2023-05-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField(max_length=20, verbose_name='Kıta adı')),
                ('text', models.TextField(max_length=2000, verbose_name='içerik')),
                ('img', models.ImageField(max_length='200', upload_to='kıta resim', verbose_name='resim')),
                ('population', models.TextField(max_length=50, verbose_name='kıta nüfüusu')),
                ('area', models.TextField(max_length=20, verbose_name='kıta yüzölçümü')),
                ('countries_total', models.TextField(max_length=20, verbose_name='kıtada ki ülke sayısı')),
                ('map', models.TextField(max_length=1000, verbose_name='kıta konumu')),
            ],
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
