# Generated by Django 4.1.7 on 2023-05-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_continents_delete_card'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Continents',
        ),
    ]
