# Generated by Django 4.1.7 on 2023-05-19 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appMy', '0003_delete_continents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField(max_length=20, verbose_name='Kıta adı')),
                ('text', models.TextField(max_length=2000, verbose_name='içerik')),
                ('img', models.ImageField(max_length='200', upload_to='kıta resim', verbose_name='resim')),
                ('population', models.TextField(max_length=50, verbose_name='kıta nüfüusu')),
                ('area', models.TextField(max_length=20, verbose_name='kıta yüzölçümü')),
                ('countries_total', models.TextField(max_length=20, verbose_name='kıtada ki ülke sayısı')),
                ('map', models.TextField(max_length=1000, verbose_name='kıta konumu')),
            ],
        ),
        migrations.CreateModel(
            name='Producht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='başlık')),
                ('text', models.TextField(max_length=300, verbose_name='açıklama')),
                ('price', models.FloatField(verbose_name='fiyat')),
                ('stok', models.IntegerField(verbose_name='adet')),
                ('date_now', models.DateField(auto_now_add=True, verbose_name='tarih ve saat')),
                ('stars', models.FloatField(verbose_name='ürün puanı')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='kulanıcı')),
            ],
        ),
    ]
