# Generated by Django 4.1.7 on 2023-05-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0005_delete_producht'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continents',
            name='area',
            field=models.CharField(max_length=50, verbose_name='kıta yüz ölçümü'),
        ),
        migrations.AlterField(
            model_name='continents',
            name='countries_total',
            field=models.CharField(max_length=50, verbose_name='kıtadaki toplam ülke'),
        ),
        migrations.AlterField(
            model_name='continents',
            name='header',
            field=models.CharField(max_length=50, verbose_name='kıta adı'),
        ),
        migrations.AlterField(
            model_name='continents',
            name='map',
            field=models.CharField(max_length=500, verbose_name='kıta konumu'),
        ),
        migrations.AlterField(
            model_name='continents',
            name='population',
            field=models.CharField(max_length=50, verbose_name='kıta nüfusu'),
        ),
    ]
