# Generated by Django 4.1.7 on 2023-05-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0006_alter_continents_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continents',
            name='img',
            field=models.FileField(upload_to=None, verbose_name='kıta resimi'),
        ),
    ]
