# Generated by Django 4.1.7 on 2023-05-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0007_alter_continents_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continents',
            name='img',
            field=models.ImageField(max_length=500, upload_to='resin', verbose_name='resim'),
        ),
    ]
