# Generated by Django 4.1.7 on 2023-05-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0008_alter_continents_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continents',
            name='map',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='konum'),
        ),
    ]
