# Generated by Django 4.1.7 on 2023-05-19 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0010_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
