# Generated by Django 4.1.7 on 2023-05-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0011_delete_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continents',
            name='map',
            field=models.CharField(max_length=50, verbose_name='link'),
        ),
    ]
