# Generated by Django 4.1.7 on 2023-05-19 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0012_alter_continents_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continents',
            name='map',
        ),
    ]
