# Generated by Django 4.1.7 on 2023-05-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0013_remove_continents_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='continents',
            name='video',
            field=models.TextField(max_length=500, null=True, verbose_name='videos'),
        ),
    ]
