# Generated by Django 4.1.7 on 2023-05-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0014_continents_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ülke adı')),
                ('text', models.TextField(max_length=5000, verbose_name='ülke içeriği')),
                ('img', models.ImageField(max_length=500, upload_to=None, verbose_name='ülke bayrağı resmi')),
            ],
        ),
    ]
