# Generated by Django 4.1.7 on 2023-05-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0017_alter_countries_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countries',
            old_name='continents_detail',
            new_name='continents',
        ),
    ]
