# Generated by Django 4.1.7 on 2023-05-19 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0018_rename_continents_detail_countries_continents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50, verbose_name='tur üleksi')),
                ('text', models.TextField(max_length=5000, verbose_name='içerik')),
                ('start', models.CharField(max_length=50, verbose_name='tur başlangıç tarihi')),
                ('end', models.CharField(max_length=50, verbose_name='tur bitiş tarihi')),
                ('price', models.CharField(max_length=50, verbose_name='fiyat')),
                ('continents', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.continents', verbose_name='kıta')),
            ],
        ),
    ]
