# Generated by Django 4.1.7 on 2023-05-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0019_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='img',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='None', verbose_name='ülke bayrağı'),
        ),
    ]
