# Generated by Django 4.1.7 on 2023-05-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0020_tour_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='end',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='start',
        ),
        migrations.AddField(
            model_name='tour',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='tur süresi'),
        ),
    ]
