# Generated by Django 4.1.7 on 2023-05-20 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0022_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='cşys',
        ),
        migrations.AddField(
            model_name='city',
            name='citty',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Şehir adı'),
        ),
        migrations.AddField(
            model_name='city',
            name='contry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.tour', verbose_name='kıta'),
        ),
    ]
