# Generated by Django 4.1.7 on 2023-05-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0023_remove_city_cşys_city_citty_city_contry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='contry',
        ),
        migrations.AddField(
            model_name='tour',
            name='city',
            field=models.ManyToManyField(blank=True, null=True, to='appMy.city', verbose_name='iehirler'),
        ),
    ]
