# Generated by Django 4.1.7 on 2023-05-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0025_alter_city_citty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='citty',
            field=models.CharField(blank=True, max_length=50, verbose_name='Şehir adı'),
        ),
    ]
