# Generated by Django 4.1.7 on 2023-05-21 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0028_tour_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='total_price',
        ),
    ]
