# Generated by Django 4.1.7 on 2023-05-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0029_remove_tour_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='total_price',
            field=models.CharField(max_length=50, null=True, verbose_name='toplam yolcu adeti'),
        ),
    ]
