# Generated by Django 4.1.7 on 2023-05-21 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0031_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
