# Generated by Django 4.1.7 on 2023-05-21 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0036_userinfo_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='username',
            new_name='user',
        ),
    ]
