# Generated by Django 4.1.7 on 2023-05-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0038_alter_userinfo_balance_alter_userinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='bakiye'),
        ),
    ]
