# Generated by Django 4.1.7 on 2023-05-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0042_alter_userinfo_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=100, verbose_name='bakiye'),
        ),
    ]
