# Generated by Django 4.1.7 on 2023-05-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0044_alter_userinfo_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
