# Generated by Django 4.1.7 on 2023-05-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0045_userinfo_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
