# Generated by Django 4.1.7 on 2023-05-22 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0048_order_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
