# Generated by Django 4.1.7 on 2023-05-22 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0049_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='order_date',
        ),
    ]
